#include <iostream.h>
#include <conio.h>
#include <cstring.h> // untuk menangani tipe data string
/**
* Program C++ yang ke..
* dibuat oleh: <tulis nama saudara>
* tempat: Lab Komputer STIKOM Poltek Cirebon
* Hari, Tanggal: Senin, tanggal 13 Sepetember 2016
*/
void main()
{
	clrscr(); //membersihkan layar
// deklarasi variabel
	int nim; //tipe data nim integer
	string nama, alamat; //tipe data alamat char
	nim=1111; //nim di isi 1111
	nama="<ganti dengan nama saudara>"; // di isi nama saudara (string)
	alamat="<ganti dengan lamat saudara>"; // di isi alamat saudara(string)
	cout << "Ini Program C++ Pertama Aku \n"; //mencetak informasi di layar
	cout << "========================\n"; //mencetak informasi di layar
	cout << "NIM : "<<nim<<"\n"; //mencetak informasi di layar
	cout << "Nama : "<<nama<<"\n"; //mencetak informasi di layar
	cout << "Alamat : "<<alamat<<"\n"; //mencetak informasi di layar
 	getch(); //menahan tampilan layar
}
